using ApplicationCore.Shared;

namespace ApplicationCore.Features.AllmoxyOrderExport.Attributes;

public static class ClosetEdgeBandingMaterial {

    public const string MATCH = "Match";

    public static string GetMatchingMaterialName(string color) {

        return MaterialNames.Select(Guess => (Guess, StringDistanceComparison.LevenshteinDistance(color, Guess)))
                            .OrderBy(d => d.Item2)
                            .First()
                            .Guess;

    }

    public static string[] MaterialNames => new string[] {
		"Match",
		"White",
		"Autum Leaves",
		"Beachwood",
		"Latitude East",
		"Latitude West",
		"Latitude North",
		"River Rock",
		"Southwester",
		"Spring Blossom",
		"Summer Breeze",
		"Niagara",
		"Mojave",
		"Winter Cherry",
		"Breakwater",
		"Appalachia",
		"After-Hours",
		"Apres-Ski",
		"Cast at First Light",
		"Stargazer",
		"Sunday Brunch",
		"Tea For Two",
		"Tete-a-Tete",
		"Winter Fun!",
		"Summertime Blues",
		"Weekend Getaway",
		"Sugar on Ice",
		"Sunset Cruise",
		"White (Viva)",
		"Black (Viva)",
		"Creme De La Creme",
		"Treasure Trove",
		"Simply Galant",
		"Home Sweet Home",
		"Black Tie",
		"New Wave",
		"White (Brava)",
		"Black (Brava)",
		"First Dance",
		"Golden Light",
		"Brass Band",
		"Sunday Stroll",
		"Ganache",
		"Night Owl",
		"Rhapsody",
		"The Chameleon",
		"First Class",
		"Fashionista",
		"Sheer Beauty",
		"Free Spirit",
		"Force of Nature",
		"Rock Solid",
		"Urban Vibe (Karisma)",
		"White Chocolate",
		"Sable Island",
		"Maritime Dune",
		"Northern Plain",
		"Tofino",
		"Laurentian Path",
		"Mariposa",
		"Rocky Mountain",
		"Chalbi Clay",
		"Milk Chocolate",
		"Fogo Harbour",
		"Ungava Bay",
		"Megantic",
		"Portobello",
		"Monaco",
		"Karoo Ash",
		"Dark Chocolate",
		"Hardrock Maple",
		"Prestige Maple",
		"Secret",
		"Candlelight",
		"Cappuccino Cherry",
		"Rustik Cherry",
		"Summer Flame",
		"Dark-Rum Cherry",
		"Brunito Cherry",
		"Ruby Planked Maple",
		"Shiraz Cherry",
		"Brushed Aluminum",
		"Tuxedo",
		"Truffle",
		"Very Chic",
		"Chocolate Pear Tree",
		"Hot Fudge",
		"Snowfall (Crystalite)",
		"White (Crystalite)",
		"Vanilla Orchid",
		"Glacier White",
		"Classic White",
		"Froth of Sea",
		"Ivory",
		"Almondine",
		"Morning Dew (Crystalite)",
		"Daybreak (Crystalite)",
		"Milky Way",
		"Slate (Crystalite)",
		"Sundown (Crystalite)",
		"Summer Drops (Folkstone)",
		"Rain Cloud",
		"Shadows (Fog Grey)",
		"Moonlight",
		"Starry Night (Crystalite)",
		"Black (Crystalite)",
		"Vanilla Orchid (Gloss)",
		"Carte Blanche (Gloss)",
		"Black (Gloss)",
		"Midnight Sun (Gloss)",
		"North Wind (Gloss)",
		"Morning Dew (Gloss)",
		"Steampunk",
		"Iron Horse",
		"Carte Blanche (Matt)",
		"Vanilla Orchid (Matt)",
		"Morning Dew (Matt)",
		"North Wind (Matt)",
		"Midnight Sun (Matt)",
		"Calm Sea",
		"Eucalyptus",
		"Sunflower",
		"Urban Vibe (Matt)",
		"Camera Obscura",
		"Black (Matt)",
		"Olmo 634",
		"Euroline 03 623",
		"Roble Frape 627",
		"Guayana 617",
		"Olivo 618",
		"Blanco",
		"Basalto",
		"Magnolia",
		"Cashmere",
		"Pale Gray",
		"Antracita",
		"Black (Brillante)",
		"Rojo",
		"Textil Plata",
		"Textil Grafito",
		"Cuzco Royal Gold",
		"Cuzco Oro",
		"Platino",
		"Bronce",
		"Titanio",
		"Cobalto",
		"Bohemian Blanco",
		"Fresno Glacial",
		"Roble Stella",
		"Roble Oasis",
		"Roble Aurora",
		"Roble Bello",
		"Roble Denver",
		"Nogal Slow",
		"Roble Colorado",
		"Roble Joplin",
		"Roble Eternity",
		"Roble Azabache",
		"Blackwood",
		"Tessuto",
		"Lino Cancun",
		"Espiga Sal",
		"Espiga Primenta",
		"Marmol Blanco",
		"Cemento",
		"Marmol Hades",
		"Super White",
		"Gris Coco",
		"Mineral Grey",
		"Gris Gu",
		"Roble Memphis",
		"Blanc",
		"Roble Dallas",
		"Roble Alabama",
		"Chicago",
		"Roble Niagara",
		"Sacramento",
		"Pino Valkiria",
		"Fresno Rosario",
		"Fresno Plata",
		"Pre-Finished Birch",
    };

}
