// DO NOT EDIT
// This file will be generated by the CI pipeline to set the correct database schema version 

namespace ApplicationCore.Schemas;

internal static class OrderingSchemaVersion {
    internal const int SCHEMA_VERSION = 1;
}
