on:
  push:
    branches: [ master ]
    paths-ignore:
    - .github/workflows/deploy_release.yml

jobs:
  
  Build:
    name: Deploy App to Preview Channel
    runs-on: windows-latest
    
    env:
      ApplicationName: DesktopHost
      WapProjectName: Package
      BuildConfiguration: Release
      ReleaseChannel: preview
      SigningCertificate: GithubCertificate.pfx      
      DeployURI: http://zacharylondono.com/orders/preview
      DeployPath: ./app_deployment/orderprocessor_artifacts/preview

    steps:

    - name: Checkout repository
      uses: actions/checkout@v3
      with:
       fetch-depth: 0 # Needed for nbgv
    
    - name: Setup NerdBank.GitVersion
      uses: dotnet/nbgv@master
      id: nbgv
    
    - name: Setup msbuild
      uses: microsoft/setup-msbuild@v1.1

    - name: Setup Node for Tailwindcss
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install Tailwindcss
      run: npm install -D tailwindcss

    - name: Use .NET Core SDK 9.x
      uses: actions/setup-dotnet@v3
      with:
       dotnet-version: 9.x

    - name: Add Github Nuget Source
      run: dotnet nuget add source --username ZachLondono --password ${{ secrets.NUGET_PASSWORD }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/ZachLondono/index.json"

    - name: Run Unit Tests
      run: |
          dotnet test .\ApplicationCore\ApplicationCore.Tests\ApplicationCore.Tests.csproj
          dotnet test .\DesktopHost\DesktopHost.Tests\DesktopHost.Tests.csproj
          dotnet test .\Companies\Companies.Tests\Companies.Tests.csproj
          dotnet test .\Orders\OrdersLoading\Orders.OrdersLoading.Tests\Orders.OrdersLoading.Tests.csproj
          dotnet test .\Orders\OrdersExporting\Orders.OrdersExporting.Tests\Orders.OrdersExporting.Tests.csproj
    
    - name: Create directory for output
      run: mkdir ${{ github.workspace }}\${{ env.ReleaseChannel }}
      
    - name: Decode certificate
      run: |
       $pfx_bytes = [System.Convert]::FromBase64String("${{ secrets.BASE64_PFX_CONTENT }}");
       $currentDirectory = Get-Location
       $certificatePath = Join-Path -Path $currentDirectory -ChildPath ${{ env.WapProjectName }} -AdditionalChildPath ${{ env.SigningCertificate }}
       [IO.File]::WriteAllBytes("$certificatePath", $pfx_bytes)
      shell: pwsh
    
    - name: Update AppxManifest
      run: |
       # Update appxmanifest. This must be done before build.
       [xml]$manifest= get-content ".\${{ env.WapProjectName }}\${{ env.WapProjectName }}.appxmanifest"
       # Set version number
       $manifest.Package.Identity.Version = "${{ steps.nbgv.outputs.SimpleVersion }}.0"
       # Update display name for preview version
       $manifest.Package.Applications.FirstChild.VisualElements.DisplayName = "$($manifest.Package.Applications.FirstChild.VisualElements.DisplayName) (preview)"
       $manifest.save(".\${{ env.WapProjectName }}\${{ env.WapProjectName }}.appxmanifest")
      shell: pwsh
    
    - name: Set channel name
      run: |
       echo -n ${{ env.ReleaseChannel }} > ".\${{ env.ApplicationName }}\channel.txt"
      shell: pwsh

    - name: Write credentials file 
      run: |
       $creds = '${{ secrets.CREDENTIALS }}'
       Out-File -FilePath ".\${{ env.ApplicationName }}\Configuration\credentials.json" -InputObject $creds
      shell: pwsh

    - name: Restore csproj
      run: dotnet restore .\${{ env.ApplicationName }}\${{ env.ApplicationName }}.csproj

    - name: Restore wapproj
      run: msbuild /t:restore .\${{ env.WapProjectName }}\${{ env.WapProjectName }}.wapproj
    
    - name: Build Appx Package
      run: |
       dotnet restore .\${{ env.ApplicationName }}\${{ env.ApplicationName }}.csproj
       msbuild /t:restore .\${{ env.WapProjectName }}\${{ env.WapProjectName }}.wapproj
       msbuild '.\${{ env.WapProjectName }}\${{ env.WapProjectName }}.wapproj' `
               /p:VersionNumber=${{ steps.nbgv.outputs.SimpleVersion }}.0 `
               /p:configuration='${{ env.BuildConfiguration }}' `
               /p:IncludeSymbols=true `
               /p:PackageCertificateKeyFile=${{ env.SigningCertificate }} `
               /p:AppInstallerUri="${{ env.DeployURI }}" `
               /p:AppxPackageDir="${{ github.workspace }}\${{ env.ReleaseChannel }}\" `
               /p:PackageName="Order Processor"
               #/p:PackageCertificatePassword=${{ secrets.PFX_KEY }} `
    
    - name: Remove the .pfx
      run: Remove-Item -path ${{ env.WapProjectName }}\${{ env.SigningCertificate }}
    
    - name: Remove appinstaller protocol
      run: |
       (Get-Content "${{ github.workspace }}\${{ env.ReleaseChannel }}\index.html").replace('ms-appinstaller:?source=', '') | Set-Content "${{ github.workspace }}\${{ env.ReleaseChannel }}\index.html"
      shell: pwsh
     
    - name: Create Release Notes
      id: release_notes
      uses: actions/github-script@v6.4.1
      env:
       COMMITS: ${{ toJSON(github.event.commits) }}
      with:
        result-encoding: string
        script: |
          const commits = JSON.parse(process.env.COMMITS);
          notes = ""
          for (const commit of commits) {
              const date = new Date(commit.timestamp)
              const timestampStr = (date.getMonth()+1) + "/" + date.getDate() + "/" + date.getFullYear() + " " + date.getHours() + ":" + ("0" + date.getMinutes()).slice(-2)
              const commitNote = ("[" + timestampStr + "] - " + commit.message + "\n").replace(/"/g, "`\"")
              notes += commitNote
          }
          return notes.trim()

    - name: Write Release Notes to File
      run: |
        echo -n "${{ steps.release_notes.outputs.result }}" > "${{ github.workspace }}\${{ env.ReleaseChannel }}\release_notes.txt"

    - name: Copy Files to Remote
      uses: garygrossgarten/github-action-scp@release
      with:
       local: ${{ github.workspace }}\${{ env.ReleaseChannel }}\
       remote: ${{ env.DeployPath }}
       host: ${{ secrets.SSH_HOST }}
       username: ${{ secrets.SSH_USER }}
       port: ${{ secrets.SSH_PORT }}
       privateKey : ${{ secrets.SSH_PRIVATE_KEY }}